CREATE TABLE TechServiceParts(
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
TechServiceId INT NOT NULL,
PartId INT NOT NULL,
FOREIGN KEY(TechServiceId) REFERENCES TechServices(Id),
FOREIGN KEY(PartId) REFERENCES Parts(Id)
);