CREATE TABLE VehicleTypes(
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
TypeName VARCHAR(50) NOT NULL CHECK(LEN(TypeName) >= 1)
);

CREATE TABLE VehicleStatuses(
Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
StatusName VARCHAR(50) NOT NULL CHECK(LEN(StatusName) >= 1)
);